#!/bin/sh

### reactorFS Filetype Typer
## defines which SQL query to use when picking backend storage
## w/ a default (hash)
## i.e. .mp3s forced to tagged mp3 servers
## SOMEBODY REWRITE THIS IN RUBY/JSON!

IFS=$'\t\n'
FILENAME="${1}"

case "${FILENAME}" in
	[0-9][0-9][0-9][0-9]* )
	  ## begins with 4 digits
	  ## hash
	  QUERY="default"
	  ;;
	*.mp3|*.mp4 )
	  ## hash w/ tags i.e. choose only servers with mp3/mp4 tagged to them
	  QUERY="tagged"
	  ;;
	* )
	  ## default
	  QUERY="default"
	  ;;
esac
